name: CI + Dependency Security

on:
  pull_request:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 14 * * 1" # Mondays 14:00 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci

      # run only if the script exist in package.json
      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test --if-present

      - name: Build
        run: npm run build --if-present

  dependency-security:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: npm audit (JSON)
        run: npm audit --json > audit.json || true

      - name: Enforce security policy (fail on high/critical)
        run: python3 scripts/risk_score.py audit.json

        # fun part  get the sboms from cyclonedx and upload them as artifacts for future use in SCA and vulnerability management tools
      - name: Generate SBOM (CycloneDX)
        run: npx --yes @cyclonedx/cyclonedx-npm --output-file sbom.json

      - name: Upload security artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-artifacts
          path: |
            audit.json
            sbom.json
  #dependabot PRs are automatically merged if the CI and dependency security checks pass, and the PR is created by it
  automerge-dependabot:
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    needs: [ci, dependency-security]
    steps:
      - name: Enable auto-merge (Dependabot PRs)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"